export const elements = {
  loader: document.querySelector('#tunerLoader'),
  themeMeta: document.querySelector('meta[name="theme-color"]'),
  presetSelect: document.querySelector('#tunerPreset'),
  modeInputs: document.querySelectorAll('input[name="tunerMode"]'),
  tuning: document.querySelector('#tuning'),
  tuningBadge: document.querySelector('#tuningBadge'),
  tuningDown: document.querySelector('#tuningDown'),
  tuningUp: document.querySelector('#tuningUp'),
  resetTuning: document.querySelector('#resetTuning'),
  micToggle: document.querySelector('#micToggle'),
  micStatus: document.querySelector('#micStatus'),
  micLevel: document.querySelector('#micLevel'),
  stage: document.querySelector('#tunerStage'),
  gaugeTicks: document.querySelector('#gaugeTicks'),
  gaugeArc: document.querySelector('#gaugeArc'),
  chevrons: document.querySelector('#tunerChevrons'),
  note: document.querySelector('#tunerNote'),
  octave: document.querySelector('#tunerOctave'),
  cents: document.querySelector('#tunerCents'),
  frequency: document.querySelector('#tunerFrequency'),
  statusText: document.querySelector('#tunerStatusText'),
  strings: document.querySelector('#tunerStrings'),
  toast: document.querySelector('#tunerToast'),
};
