export const elements = {
  loader: document.querySelector('#trainingLoader'),
  intervalRail: document.querySelector('#intervalRail'),
  sectionPanels: document.querySelectorAll('[data-learn-panel]'),
  scaleRoot: document.querySelector('#scaleRoot'),
  scaleType: document.querySelector('#scaleType'),
  scalePosition: document.querySelector('#scalePosition'),
  scaleNamesToggle: document.querySelector('#scaleNamesToggle'),
  scaleFretboard: document.querySelector('#scaleFretboard'),
  scaleExplainer: document.querySelector('#scaleExplainer'),
  scaleBadge: document.querySelector('#scaleBadge'),
  playScale: document.querySelector('#playScale'),
  anchorNote: document.querySelector('#anchorNote'),
  anchorPosition: document.querySelector('#anchorPosition'),
  playLearnInterval: document.querySelector('#playLearnInterval'),
  intervalExplainer: document.querySelector('#intervalExplainer'),
  learnFretboard: document.querySelector('#learnFretboard'),
  noteFretboard: document.querySelector('#noteFretboard'),
  notesBadge: document.querySelector('#notesBadge'),
  tuning: document.querySelector('#tuning'),
  tuningBadge: document.querySelector('#tuningBadge'),
  tuningDown: document.querySelector('#tuningDown'),
  tuningUp: document.querySelector('#tuningUp'),
  resetTuning: document.querySelector('#resetTuning'),
  intervalChecks: document.querySelector('#intervalChecks'),
  selectAllIntervals: document.querySelector('#selectAllIntervals'),
  clearIntervals: document.querySelector('#clearIntervals'),
  settingsError: document.querySelector('#settingsError'),
  toggleTraining: document.querySelector('#toggleTraining'),
  trainerSettings: document.querySelector('#trainerSettings'),
  quizIdle: document.querySelector('#quizIdle'),
  quizActive: document.querySelector('#quizActive'),
  quizSummary: document.querySelector('#quizSummary'),
  visualQuestion: document.querySelector('#visualQuestion'),
  quizFretboard: document.querySelector('#quizFretboard'),
  earQuestion: document.querySelector('#earQuestion'),
  replayQuestion: document.querySelector('#replayQuestion'),
  questionTitle: document.querySelector('#questionTitle'),
  questionNumber: document.querySelector('#questionNumber'),
  answerGrid: document.querySelector('#answerGrid'),
  answerFeedback: document.querySelector('#quizFeedback'),
  correctCount: document.querySelector('#correctCount'),
  errorCount: document.querySelector('#errorCount'),
  summaryCorrect: document.querySelector('#summaryCorrect'),
  summaryErrors: document.querySelector('#summaryErrors'),
  summaryAccuracy: document.querySelector('#summaryAccuracy'),
  toast: document.querySelector('#trainingToast'),
  themeMeta: document.querySelector('meta[name="theme-color"]'),
};

export function checkedValue(name, fallback) {
  return document.querySelector(`input[name="${name}"]:checked`)?.value || fallback;
}
